### ISSUE TITLE
Stop study if requirements are not met

### ISSUE THREAD

**Issue by EllaSoderberg** [EllaSoderberg/EmotionandLiking#1]
In the introduction, you can click radio buttons to verify that you are above 18 and so on. If you answer "no" to any of these questions, the study should stop.

**Comment by dvcarrillo** [comment]
I can take this one too.

I propose not to stop it (which requires a further validation of the data) but to disable the continue button with an indication of why it is not enabled.

**Comment by EllaSoderberg** [comment]
Good suggestion!

**Comment by dvcarrillo** [comment]
This one was harder, as we don't have directly the HTML in the builder. But now the `Continue` button is activated **only** when we agree with the 4 statements.

**PLEASE, DON'T CHANGE** any coding on the `Welcome page`, nor alter the current buttons. Ask me before if possible 😄

![image](https://user-images.githubusercontent.com/12817239/94288807-24edf180-ff58-11ea-8f29-f18cf35f921c.png)
