### ISSUE TITLE
Validate that the data is good

### ISSUE THREAD

**Issue by EllaSoderberg** [EllaSoderberg/EmotionandLiking#10]
I haven't looked much at the out-data. I think it should be good enough, but I'm not sure. Ana gave us some descriptions of what it should consist of in the slides. To see the data, you can run the study and click the hamburger button in the lower right corner.

**Comment by Geoodees** [comment]
https://labjs.readthedocs.io/en/latest/reference/data.html I tried to make this work, but did not understand it. Otherwise, I assume need to manually extract the data.

**Comment by Geoodees** [comment]
I will probably focus on this task. However, would be nice to bounce ideas with someone. jacobel@kth.se 0730412333

**Comment by EllaSoderberg** [comment]
Trough open-lab.online we can at least save all the data automatically. Have you checked it out? :)

**Comment by Geoodees** [comment]
Will check!

**Comment by Geoodees** [comment]
I started by forming how the data output should look. Linking to a google sheet for now, https://docs.google.com/spreadsheets/d/1YJm1owTWUqmXWJ2kMbzWrHCWgvmr25IbNWkQI0zW1UE/edit?usp=sharing

**Comment by Geoodees** [comment]
Ana sent a revised version, added it to the Sheet. Should be easier to apply data to that one. Looking more closely at it tonight or tomorrow.

**Comment by Geoodees** [comment]
After looking through the raw data, what is saved (more or less) is,
- Task, Block, Stimulus and each of the 3 ratings
- All personal information
- All NFC and NFE
- Response Time... Very unclear how? It's probably in ms atleast.

The rest I have trouble finding. And everything is formatted in such as way that it would take hours to shift through it.
I will look into making Data Storage work, it's perfect for what we need. Just need to set it up and understand it. Have to sit with it tomorrow.

**Comment by EllaSoderberg** [comment]
Great work, thank you!!

**Comment by Geoodees** [comment]
Ok, endgoal for now will be to solve extracting the data for after the study. I am fine with how we store the data in open-lab, should be easy to make a script to extract several .csvs while making the data analysis.

I'll make a branch, adding a counter repetition and adding comments on how LabJS counts time taken. Otherwise, everything else is fine.
