### ISSUE TITLE
Age validation

### ISSUE THREAD

**Issue by EllaSoderberg** [EllaSoderberg/EmotionandLiking#4]
When filling in the age in the demography form, the age should be in a certain interval (18-99 or so).

**Comment by dvcarrillo** [comment]
I'll get this one for me

**Comment by dvcarrillo** [comment]
![image](https://user-images.githubusercontent.com/12817239/94281821-64641000-ff4f-11ea-8dcf-11f96de84794.png)

Solved. Will add this change in a PR.
